### ISSUE TITLE
Don't recommend against PVP in the Readme

### ISSUE THREAD

**Issue by DrewFenwick** [stackbuilders/semantic-release-hackage#25]
> This is just an optional feature to enable backward compatibility when starting to use this plugin.

> We strongly recommend moving to semantic versioning to keep things simple and follow a well-known standard. But versionPrefix can save the day if changing the versioning system is not an option.

Please don't recommend people don't follow the PVP or imply that it isn't a current standard by talking about "backward" compatibility.
It isn't backward compatibility. It is PVP compatibility. Unless I've missed something, Hackage isn't being phased out.

The PVP is the version scheme you're supposed to be using for curated Hackage packages. It says so on the front page of Hackage.

> All [curated](https://hackage.haskell.org/upload#versioning_and_curation) packages should follow the [Package Versioning Policy (PVP)](https://pvp.haskell.org/).

Is there any reason to believe that statement isn't current?

Not only is PVP baked into the Hackage curation process. It is baked into the Cabal package description format. [See the `^>=` operator.](https://cabal.readthedocs.io/en/stable/cabal-package.html#pkg-field-build-depends).

It is also overwhelmingly the dominant versioning system standard of the Haskell ecosystem.

So it seems to me that switching to SemVer is a behavior which frustrates the package curation process, subverts my expectation as a potential user of the library, and undermines the features of the cabal package description format and Cabal tooling.

I'm curious what benefit there is to SemVer that outweighs these costs. 

How would two common Haskell versioning standards instead of one make things simpler?

It's a shame that what is common inside the ecosystem is not what is common outside the ecosystem but is the value of pursuing uniformity with the world *outside* the ecosystem worth the disruption it will cause *inside* the ecosystem?

**Comment by chreekat** [comment]
I'm afraid @DrewFenwick is correct. PVP *is* the semantic versioning policy for Haskell packages.

PVP actually predates SemVer. Unfortunately it was designed with references to Haskell features, so it was not adopted more widely. But the fact remains that PVP is alive and well, and it's an integral part of how Hackage works.

Luckily, since PVP *is* a semantic versioning policy, it's still a good fit for this tool! :)

**Comment by JoseLion** [comment]
Thank you so much for the feedback! It's great to hear from the community so we can improve things according to what benefits everyone.

I agree that part of the documentation can be misleading. I think the intention was to say that `semantic-release` is incompatible with PVP because of the fourth version number, so we had to add some workaround, which made using this package a bit less straightforward.

In any case, getting feedback is the best way to plan our next steps, so we will focus on improving compatibility with PVP and making changes to the documentation about PVP according to your suggestions.

Thanks again for reaching out!
