### ISSUE TITLE
Update repository's .cabal file with new version

### ISSUE THREAD

**Issue by jpvillaisaza** [stackbuilders/semantic-release-hackage#26]
When publishing a package candidate to Hackage, this updates the .cabal file with the new version, but the .cabal file in the repository is not updated. This might be confusing because the .cabal files don't match. I think this should either update the .cabal file in the repository or note that the user has to manually update the file to keep the versions synced.

As an example, [atomic-write-0.2.1.0/candidate/atomic-write.cabal](https://hackage.haskell.org/package/atomic-write-0.2.1.0/candidate/atomic-write.cabal) has the following version:

```
version: 0.2.1.0
```

But this doesn't match the version in [atomic-write.cabal](https://github.com/stackbuilders/atomic-write/blob/64eccab6492e2bab152a0cf80acbbffd437948fe/atomic-write.cabal#L2):

```
version:             0.2.0.7
```

(In the case of atomic-write, this is more confusing because there's a GitHub release for v0.2.1.0, but I don't think that's related to this project.)

**Comment by dalejo96** [comment]
Hey! 
semantic-release has another plugin called [git](https://github.com/semantic-release/git) that can be used for committing things during the release process. 
However, this is not recommended because it can lead to confusion and semantic-release does not need this value defined to know about the next version.

I recommend using the `version: 0.0.0.0` or `version: 0.0.0`
Please, take a look at this [semantic-release FAQ](https://semantic-release.gitbook.io/semantic-release/support/faq#why-is-the-package.jsons-version-not-updated-in-my-repository) for extra information regarding the version management.

I am opening a new PR explaining this in a README section because committing the new version to the .cabal file is not the responsibility of this plugin.

The released version is defined in the release candidate cabal file as you can see [here](https://hackage.haskell.org/package/atomic-write-0.2.1.0/candidate/atomic-write.cabal) for atomic-write.

Thanks for reaching out!

**Comment by dalejo96** [comment]
I updated the README to inform the users about a dependency that can be used to keep the version synced.
